Add cobalt CI (#3)
* fix cobalt_ci.yml

* Update cobalt_ci.yml

* Update cobalt_ci.yml

* Update cobalt_ci.yml

* Update cobalt_ci.yml

* Update cobalt_ci.yml

* Update cobalt_ci.yml

* Update cobalt_ci.yml

* Update cobalt_ci.yml

* Update cobalt_ci.yml

* Update cobalt_ci.yml

* Update cobalt_ci.yml

* Update cobalt_ci.yml

* add ref for auto rt

diff --git a/.github/workflows/cobalt_ci.yml b/.github/workflows/cobalt_ci.yml
--- a/.github/workflows/cobalt_ci.yml
+++ b/.github/workflows/cobalt_ci.yml
@@ -19,18 +19,57 @@ jobs:
   build:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
+    # define container
+    container:
+       image: clouden90/1d_mom6_cobalt:base
+       options: --user root
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Checkout Repository
         uses: actions/checkout@v3
-
-      # Build and Test within Docker container
-      - name: Build and Test
-        uses: docker://clouden90/1d_mom6_cobalt:base:
         with:
-          args: |
-            ls -l -h
-            pwd
-            which wget
+          submodules: recursive
+
+      # Install wget and get data
+      - name: Install wget and get data
+        run: |
+          apt-get update
+          apt-get install -y wget
+          cd /opt
+          wget https://gfdl-med.s3.amazonaws.com/OceanBGC_dataset/1d_datasets.tar.gz
+          tar -zxvf 1d_datasets.tar.gz
+          rm -rf 1d_datasets.tar.gz
+
+      # git clone MOM6_OBGC_examples and replace ocean_BGC
+      - name: git clone MOM6_OBGC_examples and build mom6sis2-cobalt
+        run: |
+          cd ..
+          git clone https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/MOM6_OBGC_examples.git --recursive
+          rm -rf MOM6_OBGC_examples/src/ocean_BGC
+          cp -r ocean_BGC MOM6_OBGC_examples/src
+          cd MOM6_OBGC_examples/builds
+          ./linux-build.bash -m docker -p linux-gnu -t prod -f mom6sis2
+          
+
+      # run 1D mom6sis2-cobalt test
+      - name: 1D mom6sis2-cobalt test
+        run: |
+          cd ../MOM6_OBGC_examples/exps
+          ln -fs /opt/datasets ./
+          cd OM4.single_column.COBALT.p4
+          mkdir RESTART
+          mpirun --allow-run-as-root -np 1 ../../builds/build/docker-linux-gnu/ocean_ice/prod/MOM6SIS2
+
+      - name: baseline check
+        run: |      
+          cd ../MOM6_OBGC_examples/exps/OM4.single_column.COBALT.p4
+          mkdir -p ref
+          cp ../../src/ocean_BGC/.github/ref/OM4.single_column.COBALT.p4/docker-linux-gnu/* ./ref
+          # check ocean.stats 
+          diff -q ref/ocean.stats ./ocean.stats > /dev/null || { echo "Error: ocean.stats are different, check and update ref! Exiting now..."; exit 1; }
+          # check MOM.res.nc
+          ncdump ref/MOM.res.nc > org_ref.txt
+          ncdump RESTART/MOM.res.nc > new_ref.txt
+          diff -q ./org_ref.txt ./new_ref.txt > /dev/null || { echo "Error: MOM.res.nc are different, check and update ref! Exiting now..."; exit 1; }
